SET LINESIZE 500
SET PAGESIZE 66

-- Report: Show all the available products using select statements
SET ECHO ON
SPOOL C:\Products.txt

COLUMN product_id HEADING "PRODUCT_ID" FORMAT 999
COLUMN product_name HEADING "PRODUCT_NAME" FORMAT A30
COLUMN product_description HEADING "PRODUCT_DESCRIPTION" FORMAT A50
COLUMN product_weight HEADING "PRODUCT_WEIGHT" FORMAT 999.999
COLUMN category_id HEADING "CATEGORY_ID" FORMAT 999
COLUMN price HEADING "PRICE" FORMAT $999.99 
COLUMN product_stock HEADING "PRODUCT_STOCK" FORMAT 999

SELECT * FROM products;

SPOOL OFF
SET ECHO OFF
